---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jjbeauty/jjbeauty_app/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[!.]* $DEPLOYPATH 2>/dev/null || true
    - cd $DEPLOYPATH && /usr/local/bin/npm install --production=false
    - cd $DEPLOYPATH && /usr/local/bin/npm run build
