---
deployment:
  tasks:
    - /bin/cp -R * /home/jjbeauty/jjbeauty_app/
    - /bin/cp -R .[!.]* /home/jjbeauty/jjbeauty_app/ 2>/dev/null || true
    - cd /home/jjbeauty/jjbeauty_app/ && /usr/local/bin/npm install --production=false
    - cd /home/jjbeauty/jjbeauty_app/ && /usr/local/bin/npm run build
